### ISSUE TITLE
Initial suggestions for plugin release

### ISSUE THREAD

**Issue by misraved** [francois2metz/steampipe-plugin-gitguardian#1]
Thanks @francois2metz for this fantastic new plugin. The structure looks good and I successfully managed to install the plugin and have a go at it. 

Before publishing it to the hub, we have a few minor suggestions:

1. The README file needs to include a reference to the social graphics icon. For instance something like the following:
```
![image](https://hub.steampipe.io/images/plugins/turbot/pagerduty-social-graphic.png)

# PagerDuty Plugin for Steampipe

Use SQL to query infrastructure services, teams, escalation policies and more from your PagerDuty account.
```
2. The format of the README file is missing essential links for slack community channel links, example query and a link to get the token of GitGuardian.

3. Can we update the .gitignore file to include other files per https://github.com/turbot/steampipe-plugin-aws/blob/main/.gitignore

4. The `config/gitguardian.spc` file should link to https://dashboard.gitguardian.com/workspace/306146/api/personal-access-tokens instead of https://dashboard.gitguardian.com/api to provide a direct link to get the token. I think we can add similar references in the README and `docs/index.md` files.

5. The display_name should be GitGuardian and not Gitguardian. I think we should update any such references in README and `docs/index.md` files.

6. The example queries in the table docs are missing a `;` at the end of them.

7. In the `gitguardian_audit_log` table certain columns like `member_id` and `api_token_id` are of the int data type, shouldn't they be string data type?

8. We have a typo in the description of `occurrences_count` in the `gitguardian_secret_incident` table. It should be `occurrences` instead of `occurences`.

9. Can we add a few more examples in the table docs of the `gitguardian_source` table? Something like:

List sources where the last scan failed
```
select
  id,
  url,
  health
from
  gitguardian_source
where
  last_scan_status = 'failed';
```

List open incidents
```
select
  id,
  url,
  open_incidents_count
from
  gitguardian_source;
```

10. Does the API support automatic backoff and retry, max concurrency settings? Please check https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion for more information.

11. For the initial release in the `CHANGELOG` file, can we list the new tables that have been added?

Overall the changes should be very minimal. The plugin looks ready for release. Thanks once again for the contribution and please let me know in case you have any questions about the above-mentioned points 👍 .

**Comment by francois2metz** [comment]
Hi @misraved, thanks for the review.
>     1. The README file needs to include a reference to the social graphics icon. For instance something like the following:

I have no such social graphic for now. 

> 
>     2. The format of the README file is missing essential links for slack community channel links, example query and a link to get the token of GitGuardian.

This seems to change from time to time. This seems to duplicate the docs/index.md file.

> 
>     3. Can we update the .gitignore file to include other files per https://github.com/turbot/steampipe-plugin-aws/blob/main/.gitignore

Most of them seems to be editor related files. A global gitignore file solve this problem.

>     4. The `config/gitguardian.spc` file should link to https://dashboard.gitguardian.com/workspace/306146/api/personal-access-tokens instead of https://dashboard.gitguardian.com/api to provide a direct link to get the token. I think we can add similar references in the README and `docs/index.md` files.

Unfortunatly, the link you provided is specific to each workspace. This is why i haven't be able to include a direct link to the personal access token page.

> 
>     5. The display_name should be GitGuardian and not Gitguardian. I think we should update any such references in README and `docs/index.md` files.

Oups, fixed.

> 
>     6. The example queries in the table docs are missing a `;` at the end of them.

Fixed.

> 
>     7. In the `gitguardian_audit_log` table certain columns like `member_id` and `api_token_id` are of the int data type, shouldn't they be string data type?

They are in fact `int`.

> 
>     8. We have a typo in the description of `occurrences_count` in the `gitguardian_secret_incident` table. It should be `occurrences` instead of `occurences`.

Fixed

> 
>     9. Can we add a few more examples in the table docs of the `gitguardian_source` table? Something like:
> 
>  [...]

Fixed.

>     10. Does the API support automatic backoff and retry, max concurrency settings? Please check https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion for more information.

The API does not support that. I'm not yet familiar with the retry mechanism in Steampipe. I need to find a way to test it and i'll probably apply it to my other plugins when relevant.

>     11. For the initial release in the `CHANGELOG` file, can we list the new tables that have been

Fixed !

**Comment by misraved** [comment]
Thanks @francois2metz for working on the fixes 👍 .

I will have one final look into this, post which we can go for the release 😄 .

**Comment by misraved** [comment]
The changes look great 👍 .

Closing the issue and pushing for a plugin release 🎉 .
