### ISSUE TITLE
Support the "detector" response attribute for secret incidents

### ISSUE THREAD

**Issue by orf** [francois2metz/steampipe-plugin-gitguardian#7]
Hello!
This project looks really awesome, thank you for making it.

I'm looking to fetch the `detector` attribute from the list secret incidents endpoint ([docs here](https://api.gitguardian.com/docs#operation/list-incidents)).

I'm not familiar with the steampipe plugin architecture, but I can try and make a pull request that adds these attributes as flat columns? i.e `select detector_name, detector_display_name from gitguardian_secret_incident`?

**Comment by francois2metz** [comment]
Hi @orf and thanks.

The `dectector` seems to be supported by the library https://github.com/Gaardsholt/go-gitguardian/blob/6ea8ace747890da4e4dc2ed68bff755f84f81764/incidents/Types.go#L19C7-L19C7. 
So adding them should be pretty straightfoward similar to https://github.com/francois2metz/steampipe-plugin-gitguardian/blob/4ab375f76d6afeabe25791d692eac50ee16ef746/gitguardian/table_gitguardian_source.go#L73-L76. 
Feel free to open a PR.

**Comment by orf** [comment]
Thank you so much @francois2metz. I've had a crack at it here: https://github.com/francois2metz/steampipe-plugin-gitguardian/pull/8
